# Generated by Django 5.2.13 on 2026-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecoordinates',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='placecoordinates',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
