version: '3.8'

services:
  frontend-builder:
    build:
      context: .
      dockerfile: Dockerfile.frontend.builder
    container_name: frontend_builder
    volumes:
      - ./frontend:/app/frontend
    profiles:
      - builder

  django-collectstatic:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django_collector
    volumes:
      - ./frontend:/app/frontend
    command: python manage.py collectstatic --noinput
    profiles:
      - builder

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: star_burger_web
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app/frontend
      - ./media:/app/media