FROM node:16.16-slim

WORKDIR /app

COPY package*.json ./

RUN npm ci --dev

COPY bundles-src ./bundles-src
COPY assets ./assets

CMD ["./node_modules/.bin/parcel", "watch", "bundles-src/index.js", "--dist-dir", "bundles", "--public-url", "./"]