# Generated by Django 5.2.13 on 2026-05-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_rename_first_name_order_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('new_order', 'Обработка заказа'), ('order_accepted', 'Заказ принят'), ('order_delivery', 'Заказ доставляется'), ('completed_order', 'Заказ выполнен')], default='new_order', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
