# Generated by Django 5.2.13 on 2026-05-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('new_order', 'Необработанный'), ('order_accepted', 'Принят'), ('order_delivery', 'Доставляется'), ('completed_order', 'Выполнен')], default='new_order', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
