# Generated by Django 5.2.13 on 2026-05-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_called_at_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличными'), ('electronic', 'Электронно')], db_index=True, max_length=20, null=True, verbose_name='Способ оплаты'),
        ),
    ]
