# Generated by Django 5.2.13 on 2026-05-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличными'), ('electronic', 'Электронно')], db_index=True, default='cash', max_length=20, null=True, verbose_name='Способ оплаты'),
        ),
    ]
